# Generated by Django 3.0.6 on 2020-05-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_activityperiod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
    ]
